# bind c new-window -c '#{pane_current_path}'
# bind \ split-window -h -c '#{pane_current_path}'
# bind - split-window -v -c '#{pane_current_path}'

# Use True Color
# set -g default-terminal "screen-256color"
# set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g mode-keys vi

set -g escape-time 1
set -g base-index 1
set -g pane-base-index 1

set -g mouse on
set -g status-interval 1

set -g renumber-windows on

# yank
set -s copy-command 'pbcopy' 
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# reload configuration
bind r source-file ~/.tmux.conf \; display "Reloaded"

# pane control
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind c new-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind '"' split-window -vc "#{pane_current_path}"
bind-key g run-shell "bash ~/repos/github.com/tomato3713/dotfiles/tmux-session.sh"

# Status
set -g status on
set -g status-keys vi

# Tools
bind C-d popup -xC -yC -w95% -h95% -E -d "#{pane_current_path}" "gitui"

# Plugins
# tmux-power
set -g @tmux_power_theme 'sky'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'

# ===================================
# Auto start tmux and restore
# ===================================

# auto start terminal
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm'

# auto restore tmux
set -g @continuum-restore 'on'

set -g @plugin 'wfxr/tmux-power'
setw -g window-status-format "#{pane_current_path}".

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
