# --- AI Support ---
[[plugins]]
repo = 'https://github.com/github/copilot.vim'
on_event = ['InsertEnter']
lua_source = '''
  vim.g.copilot_no_maps = true
  -- vim.g.copilot_hide_during_completions = true
  vim.g.copilot_filetypes = { text = true }
'''

[[plugins]]
repo = 'https://github.com/CopilotC-Nvim/CopilotChat.nvim'
depends = ['copilot.vim', 'plenary.nvim']
rev = 'canary'
lua_source = '''
  require('rc.copilot')
'''
