# --- Colorscheme
[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'vigoux/oak'

[[plugins]]
repo = 'tanvirtin/monokai.nvim'
hook_source = '''
  au VimEnter * nested colorscheme monokai
'''

[[plugins]]
repo = 'folke/tokyonight.nvim'
lua_source = '''
require('tokyonight').setup {
  style = 'night',
  transparent = false,
  terminal_colors = true,
}
'''

[[plugins]]
repo = 'fenetikm/falcon'
