# --- Language Server Protocol ---
[[plugins]]
repo = 'https://github.com/williamboman/mason.nvim'

[[plugins]]
repo = 'https://github.com/williamboman/mason-lspconfig.nvim'

[[plugins]]
repo = 'https://github.com/neovim/nvim-lspconfig'
depends = ['mason.nvim', 'mason-lspconfig.nvim', 'nvim-cmp']
on_event = ['BufRead']
lua_source = '''
require('rc.nvim-lspconfig')
'''

# [[plugins]]
# repo = 'https://github.com/soulis-1256/eagle.nvim'
# lua_source = '''
# require("eagle").setup({})
#
# vim.o.mousemoveevent = true
# '''

# ---- Additional LS support ----
# -------- LuaLS --------
[[plugins]]
repo = 'https://github.com/folke/lazydev.nvim'
on_ft = ['lua']
lua_source = '''
require("lazydev").setup()
'''
