# --- Snippets
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = 'InsertEnter'
depends = ['friendly-snippets']
lua_add = '''
  vim.keymap.set({'i', 's'}, '<C-f>',  function()
      return vim.fn['vsnip#jumpable'](1) == 1 and '<Plug>(vsnip-jump-next)' or '<C-f>'
  end, { expr = true, noremap = false })
  vim.keymap.set({'i', 's'}, '<C-b>',  function()
      return vim.fn['vsnip#jumpable'](-1) == 1 and '<Plug>(vsnip-jump-prev)' or '<C-b>'
  end, { expr = true, noremap = false })

  -- vim.g.vsnip_filetypes = {}
  vim.g.vsnip_snippet_dir = vim.fn.expand('~/.config/nvim/snippets')
'''

# snippets collections
[[plugins]]
on_source = ['vim-vsnip']
repo = 'rafamadriz/friendly-snippets'
